SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TreasureCard](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[PlayerID] [int],
	[Name] [varchar](max) NOT NULL,
	[IsFound] [BIT],
	[Image] [varchar] (max) NOT NULL,
 CONSTRAINT [PK_TreasureCard] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO
SET ANSI_PADDING OFF
GO
SET IDENTITY_INSERT [dbo].[TreasureCard] ON 